# Generated by Django 5.0.9 on 2024-11-07 18:26

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0121_customfield_related_object_filter'),
        ('netbox_subnet_audit_updated', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecordUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('record', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subnet_audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='netbox_subnet_audit_updated.subnetauditupdated')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
