# Generated by Django 5.0.9 on 2024-11-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_subnet_audit_updated', '0002_auditrecordupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnetauditupdated',
            name='status',
            field=models.CharField(default='auditing', max_length=30),
        ),
    ]
