# Generated by Django 5.0.9 on 2024-11-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_subnet_audit_updated', '0003_alter_subnetauditupdated_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnetauditupdated',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subnetauditupdated',
            name='status',
            field=models.CharField(default='queued', max_length=30),
        ),
    ]
