# Generated by Django 5.0.9 on 2024-11-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_subnet_audit_updated', '0005_subnetauditupdated_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnetauditupdated',
            name='user',
        ),
    ]
