# Generated by Django 5.0.9 on 2024-12-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_subnet_audit_updated', '0007_subnetauditupdated_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnetauditupdated',
            name='stop_requested',
            field=models.BooleanField(default=False),
        ),
    ]
