# Generated by Django 5.0.9 on 2024-12-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_subnet_audit_updated', '0008_subnetauditupdated_stop_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnetauditupdated',
            name='stop_requested',
        ),
    ]
