# Generated by Django 5.0.9 on 2024-12-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_subnet_audit_updated', '0009_remove_subnetauditupdated_stop_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnetauditupdated',
            name='subnet',
            field=models.CharField(max_length=43),
        ),
    ]
