# Generated by Django 5.0.9 on 2024-12-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_subnet_audit_updated', '0010_alter_subnetauditupdated_subnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnetauditupdated',
            name='subnet',
            field=models.GenericIPAddressField(),
        ),
    ]
