# Generated by Django 5.0.9 on 2024-12-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_subnet_audit_updated', '0011_alter_subnetauditupdated_subnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnetauditupdated',
            name='active_ips',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
