# Generated by Django 5.0.9 on 2024-12-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_subnet_audit_updated', '0012_subnetauditupdated_active_ips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnetauditupdated',
            name='active_ips',
        ),
    ]
