# Generated by Django 5.0.9 on 2024-12-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_subnet_audit_updated', '0013_remove_subnetauditupdated_active_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='subnetauditupdated',
            name='active_ips',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
