# Generated by Django 5.0.9 on 2024-12-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_subnet_audit_updated', '0015_alter_subnetauditupdated_active_ips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnetauditupdated',
            name='active_ips',
            field=models.JSONField(default=list),
        ),
    ]
